### ISSUE TITLE
Deploy/Retract Bug on Scene Changes

### ISSUE THREAD

**Issue by FirroSeranel** [UmbraSpaceIndustries/USI-LS#236]
Since the release on 3/17/17, the Habitation and Converter modules remain active on scene change, which is good, but...

Now all deployable modules (Karibou landing legs and Cargo Bay Doors) also deploy, but with bugs.

Legs/doors are graphically deployed, but the UI displays both "Deploy" and "Retract" buttons simultaneously. Retract buttons don't function. Deploy buttons skip the animation to the retracted phase, then display deploy animations normally. At the end of deploy animations, the Deploy buttons go away, and from then on, everything acts correctly until the next scene change.

The same save game I provided before will demonstrate this. Reuploading for ease.

[Habitat  Module Bug.zip](https://github.com/BobPalmer/USI-LS/files/853008/Habitat.Module.Bug.zip)

**Comment by BobPalmer** [comment]
Separate issue, fixed in an upcoming patch
