### ISSUE TITLE
Crew stops consuming EC when time warp is more then 100x

### ISSUE THREAD

**Issue by Winged03** [UmbraSpaceIndustries/USI-LS#240]

**Comment by Winged03** [comment]
Figured out that this only happens on

**Comment by jd284** [comment]
This is a stock "feature".

**Comment by BobPalmer** [comment]
Really more a case that consumption for converters drops - this is to prevent battery overrun.  There is a bit of math involved, but in general it's pretty optimistic.  Closing as this is not a defect in USI-LS
