### ISSUE TITLE
Wrong Year Times

### ISSUE THREAD

**Issue by voicey99** [UmbraSpaceIndustries/USI-LS#242]
USI-LS seems to define a year as 425 Kerbin-days, when instead it's actually 426 (plus a bit) days. This means a value calculated and displayed in the VAB of 3 years and 59 days actually equates to 3 years and 56 days, and this slight mismatch can become quite significant over long timescales.

**Comment by theRagingIrishman** [comment]
Ya the offending line is line 16 in LifeSupportUtilities.cs. I'll fix it.
