### ISSUE TITLE
How to calc the time of travel?

### ISSUE THREAD

**Issue by NachtSterben** [UmbraSpaceIndustries/USI-LS#246]
Hello! I don't know how to calculate the time of travel for platen or moons, so I can't calc a needed amount of supply for my crew for 1 or 2 or 3 person in flight. Can you explain me how to calc or maybe there are some mods for this? Sorry for my rude english I'm a russian speaking man. I hope that you can understand what I try to explain and my question. Thanks for help. Arthur.

**Comment by Gnurfos** [comment]
Hi. Please post such questions preferably on [the forums](http://forum.kerbalspaceprogram.com/index.php?/topic/154587-122-modular-kolonization-system-mks), as it's more of a discussion than a bug report. To answer your question, use a delta-v map ([example](http://forum.kerbalspaceprogram.com/index.php?/topic/87463-121-community-delta-v-map-25-dec-6th/)), which will give you both the transfer time and the required delta-v (very important too).

**Comment by BobPalmer** [comment]
Closing as this is a general KSP question
