### ISSUE TITLE
Crew remain tourists after docking resupply vehicle

### ISSUE THREAD

**Issue by drewcassidy** [UmbraSpaceIndustries/USI-LS#253]
After docking a resupply vehicle with my station, the crew onboard which were starved remained as tourists.

Attached: the log file, before and after I fixed it by hacking the quicksave file
[KSP.txt](https://github.com/UmbraSpaceIndustries/USI-LS/files/1087164/KSP.txt)

**Comment by BobPalmer** [comment]
What was their hab time?  In this example, a log file will not help - I'd need either a save file or a lot more details.  Going to close this one, re-open if you have this info (or have the info if it happens again).

**Comment by drewcassidy** [comment]
Hab was indefinite, It was set to the default settings

heres the backup I made before attempting the fix. The relavent ship is the "Orbital Station Alpha", which I think should only require Near Future Tech, Dmagic orbital sciences, and KIS in case you have to actually load it
[quicksave copy.txt](https://github.com/UmbraSpaceIndustries/USI-LS/files/1100015/quicksave.copy.txt)
