### ISSUE TITLE
Localisation Bug

### ISSUE THREAD

**Issue by voicey99** [UmbraSpaceIndustries/USI-LS#259]
**copypasted from Kerbal101's post in the thread**

I have both LS and MKS installed, so I am not sure which one has the problem, but its definitely USI bug.
Basically, in non-English KSP versions, if any kerbal runs out of habitation time, then upon recovery its "crew =" value is assigned a translated word for that profession in the local language.
So, instead of "crew = pilot", that specific kerbal is saved as "crew = пилот" in ru version, - that strips all kerbals below him on the roster from all abilities, but in save file only that string remains corrupted.
I encountered corruptions of "pilot" and "scientist".

Changing that one word manually with text editor un-corrupts the kerbal roster - but it repeats every time habitation check fails.

(http://forum.kerbalspaceprogram.com/index.php?/topic/162273-13ru-and-usi-kerbals-loose-all-stats) -more details about this bug. Thank you.

**Comment by DasSkelett** [comment]
Encountered this to, with German Translation, where my Scientist got classified as "Wissenschaftler", leading to a corrupted save file.

**Comment by DasSkelett** [comment]
Okay, I think I found the bug:
When setting the Kerbals to "Tourist"-trait after being , you save `crew.experienceTrait.Title` (wich gets translated) as `oldkStat.OldTrait` instead of `ExperienceTrait.TypeName` (wich shouldn't be translated, if I'm reading the documentation right...)

**Comment by Fat-Zer** [comment]
Run into this just now, could you please merge/cherry-pick it to master?

cast @BobPalmer (I hope, I'm not anoying)

**Comment by cake-pie** [comment]
@DasSkelett the API docs do indeed seem to imply that Title is the localized display string whereas TypeName is not supposed to be localized. Unfortunately, that is not the behavior: in practice, both get translated. See: [write-up and test code](https://github.com/cake-pie/CommunityTraitIcons/wiki/Obtaining-a-Kerbal's-specialization-class-type-(ExperienceTrait-name))
