### ISSUE TITLE
Life support timer stops when EC runs out

### ISSUE THREAD

**Issue by gracepetryk** [UmbraSpaceIndustries/USI-LS#26]
Whenever a vessel runs out of electric charge, the timer in the status window stops counting down, if this is intended behavior it should be made clear what is going on

**Comment by Gnurfos** [comment]
@johnpetryk sorry this is an old one: could you check it's still happening ? If so, could you give details ? Is the vessel focused/loaded ? Are you talking about the EC timer stopping or some other timer like supplies ?

**Comment by ilikebits** [comment]
I'm seeing this as well. When a vessel is unfocused and has no EC, then neither its supplies nor EC timers count down.
