### ISSUE TITLE
Settings not working

### ISSUE THREAD

**Issue by HurricanKai** [UmbraSpaceIndustries/USI-LS#272]
So, ive Started a Game with LS, but its to hard for a noob like me.
so ive gone into the config, and changed every value controlling effects to 0.
But after starting a *new* game they still got Tourists
Sorry for this Bad English. :)

Config:

LIFE_SUPPORT_SETTINGS
{
	SupplyTime = 324000			//How many seconds before Kerbals are affected by no supplies
	ECTime = 324000				//How many seconds before Kerbals are affected by no EC
	EVATime = 21600				//How many seconds before ill effects on EVA
	ECAmount = 0.01				//EC per Kerbal per second						
	SupplyAmount = 0.0005		//Supplies consumed per Kerbal per second
	WasteAmount = 0.0005		//Mulch produced per Kerbal per second
	NoSupplyEffect = 0		//Effect if a Kerbal has no supplies
	NoSupplyEffectVets = 0		//Effect if a Kerbal is a vet and has no supplies
	NoECEffect = 0				//Effect if a Kerbal has no EC
	NoECEffectVets = 0			//Effect if a Kerbal is a vet and has no EC
	EVAEffect = 0				//Effect if a Kerbal exceeds EVA time		
	EVAEffectVets = 0			//Effect if a Kerbal is a vet and exceeds EVA time
	NoHomeEffect = 0			//Effect if a Kerbal becomes homesick
	NoHomeEffectVets = 0		//Effect if a Kerbal is a vet and becomes homesick
	HabMultiplier = 1			//Bonus to hab values (1 = default = 100% of the part's rated value)
	HomeWorldAltitude = 100000000	//Altitude on Kerbin that negative effects are removed
	BaseHabTime = 0.25	//How long can 1 crew capacity support 1 Kerbal, expressed in Kerbal Months
	ReplacementPartAmount = 0	//How fast life support equipment and habs 'wears out'
	HabRange = 150				//How close we need to be to use other vessel's habitation modules and recyclers.
	EnableRecyclers = true		//Use resource recyclers?  Not the same as resource converteres like greenhouses!
	VetNames = Jebediah,Valentina,Bill,Bob	
	ScoutHabTime = 9180000
	PermaHabTime = 459000000
}

**Comment by BobPalmer** [comment]
That config only works for new games, it does not change your current settings.  To change your current settings in a save, click the green cube icon at the space center.

Also, changing settings will not revert tourists - you will need to get them back to Kerbin, or give them supplies/increase their hab time.
