### ISSUE TITLE
No Longer Compatible with StationPartsExpansionRedux

### ISSUE THREAD

**Issue by LithoBrake** [UmbraSpaceIndustries/USI-LS#286]
Kerbals are no longer happy in the station due to lost "Start Habitation" option of SPER parts

**Comment by tjdeckard** [comment]
StationPartsExpansionRedux needs to be updated to reflect changes made to converters in USITools. The parts in USI-LS or MKS can be used as an example of which PartModules need to be present on the SPER parts in order for them to continue supporting USI-LS functionality.
